Use metrics-graphics from npm instead of using <script> tags
index.html should fail with [TypeError: curve is not a function](https://github.com/mozilla/telemetry-dashboard/issues/339)